export const CHANGE_INPUT_ACTION = 'CHANGE_INPUT_ACTION';
export const GET_USER_ACTION = 'GET_USER_ACTION';
export const LOGIN_USER_ACTION = 'LOGIN_USER_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const CREATE_USER_ACTION = 'CREATE_USER_ACTION';
